---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd

platforms:
  - name: debian-9
  - name: centos-7
    driver_config:
      image: saltstack/centos-7-minimal
  - name: ubuntu-17.10

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: packages
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    packages.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - packages

verifier:
  name: inspec
  sudo: false
  # cli, documentation, html, progress, json, json-min, json-rspec, junit
  format: cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: deb
    provisioner:
      state_top:
        base:
          '*':
            - packages
    excludes:
      - centos-7
  - name: rpm
    provisioner:
      dependencies:
        - name: epel
          repo: git
          source: https://github.com/saltstack-formulas/epel-formula.git
      state_top:
        base:
          '*':
            - epel
            - packages
      pillars-from-files:
        packages.sls: test/integration/default/pillar.example.redhat
      pillars:
        top.sls:
          base:
            '*':
            - epel
            - packages
        epel.sls:
          disabled: false
    excludes:
      - debian-9
      - ubuntu-17.10

